#!/bin/bash
# Set up the vendored poster-studio Next.js app for grsai-studio.
#
# Idempotent: safe to re-run. Clones if missing, writes .env.local (Grsai-only
# provider), applies the grsai-studio integration patches (GRS AI 图库 tab),
# installs deps, and builds.
#
# Usage: bash scripts/setup-poster-studio.sh

set -euo pipefail

DIR="$(cd "$(dirname "$0")/.." && pwd)"
PS_DIR="$DIR/poster-studio"
REPO="https://github.com/joeseesun/poster-studio.git"
# Pinned upstream commit. The patches/snapshots are derived against this
# revision; upstream main can move and break the build (e.g. fabric type
# changes), so we fetch this exact commit. Override with POSTER_STUDIO_REF.
POSTER_STUDIO_REF="${POSTER_STUDIO_REF:-64c097567c5865ab47a165321849331d972455a3}"

# 1. Toolchain check.
command -v node >/dev/null 2>&1 || { echo "❌ Node.js not found. Install Node 18+ first."; exit 1; }
command -v npm >/dev/null 2>&1 || { echo "❌ npm not found."; exit 1; }

# 2. Clone if missing.
if [[ ! -d "$PS_DIR/.git" ]]; then
  echo "⬇️  Cloning poster-studio @ $POSTER_STUDIO_REF into $PS_DIR ..."
  rm -rf "$PS_DIR"
  git init "$PS_DIR"
  git -C "$PS_DIR" remote add origin "$REPO"
  git -C "$PS_DIR" fetch --depth 1 origin "$POSTER_STUDIO_REF"
  git -C "$PS_DIR" checkout FETCH_HEAD
fi

# 3. Write .env.local (Grsai-only provider; overwritten each run).
#    poster-studio runs at root on its own port (:8100); AI generation is
#    routed to FastAPI's Grsai wrapper.
cat > "$PS_DIR/.env.local" <<'EOF'
# Generated by grsai-studio/scripts/setup-poster-studio.sh — do not commit.
# Grsai is the only image model; AI calls are proxied through FastAPI.

NEXT_PUBLIC_SITE_URL=http://127.0.0.1:8100
NEXT_PUBLIC_UMAMI_SRC=
NEXT_PUBLIC_UMAMI_WEBSITE_ID=
NEXT_PUBLIC_ENABLE_BUILT_IN_JIMENG=false
NEXT_PUBLIC_GRSAI_ORIGIN=http://127.0.0.1:8099

AI_IMAGE_PROVIDER_ID=custom
AI_IMAGE_API_KEY=local
AI_IMAGE_API_ENDPOINT=http://127.0.0.1:8099/api/poster/generate
AI_IMAGE_MODEL_ID=grsai
AI_IMAGE_AUTH_HEADER=bearer
AI_IMAGE_REQUEST_FORMAT=seedream

JIMENG_BUILT_IN_ENABLED=false

QINIU_ACCESS_KEY=
QINIU_SECRET_KEY=
REMOVE_BG_API_KEY=
UNSPLASH_ACCESS_KEY=
KV_REST_API_URL=
KV_REST_API_TOKEN=
KV_REST_API_READ_ONLY_TOKEN=
EOF
echo "📝 Wrote .env.local"

# 3b. Apply grsai-studio integration patches (GRS AI 图库 tab in the picker).
python3 "$DIR/scripts/patch_poster_studio.py"

# 4. Install dependencies if missing.
if [[ ! -d "$PS_DIR/node_modules" ]]; then
  echo "📦 Installing dependencies (first run, may take a few minutes) ..."
  (cd "$PS_DIR" && npm install)
else
  echo "✅ node_modules present"
fi

# 5. Build if missing. NOTE: NEXT_PUBLIC_* values are baked at build time —
#    delete poster-studio/.next and re-run if you change them.
if [[ ! -d "$PS_DIR/.next" ]]; then
  echo "🔨 Building poster-studio (first run, may take a few minutes) ..."
  (cd "$PS_DIR" && npm run build)
else
  echo "✅ .next build present"
fi

echo "🎉 poster-studio is ready. Start everything with: bash start.sh"
